# Generated by Django 4.0.6 on 2022-07-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultImg',
            fields=[
                ('img_id', models.BigAutoField(help_text='ResultImg ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SrcImg',
            fields=[
                ('img_id', models.BigAutoField(help_text='ResultImg ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractText',
            fields=[
                ('text_id', models.BigAutoField(help_text='Extract Text ID', primary_key=True, serialize=False)),
                ('src_text', models.TextField(blank=True, help_text='source text', null=True)),
                ('trs_text', models.TextField(blank=True, help_text='result text', null=True)),
                ('coordinate', models.TextField(help_text='coordinate')),
                ('res_img_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ResultImg', to='textExtract.resultimg')),
                ('src_img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SrcImg', to='textExtract.srcimg')),
            ],
        ),
    ]
