version: "3.7"

services:
  django:
    container_name: django
    build: ./backend/
    volumes:
      - ./backend:/backend/
      - media_volume:/backend/media
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 convertoon.wsgi:application
    networks:
      - backend_network

  backend-server:
    container_name: nginx-back
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - media_volume:/backend/media
    ports:
      - "80:80"
    depends_on:
      - django
      - react
    networks:
      - backend_network

  react:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/:/frontend"
      - "/frontend/node_modules"
    stdin_open: true
    tty: true
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
volumes:
  media_volume:
