# Generated by Django 4.0.6 on 2022-07-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='src_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tar_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_text', models.TextField()),
                ('tar_text', models.TextField()),
                ('coordinate_xy', models.TextField()),
                ('src_img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textApp.src_img')),
                ('tar_img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textApp.tar_img')),
            ],
        ),
    ]
